### ISSUE TITLE
Is this project still maintained? Any plans to convert it into a Cmake project?

### ISSUE THREAD

**Issue by soulslicer** [PRiME-project/PRiMEStereoMatch#2]

**Comment by CLeechELEC** [comment]
The project is not being actively worked on at present, however it is still maintained and work is planned for the near future. As a result, bugs reported will take longer to be rectified.
The program can easily be compiled using make. Please provide justification for converting it to a cmake project. If demand is there, then a cmake project can be constructed.

**Comment by soulslicer** [comment]
making it a cmake project allows it integration into many robotic libraries, such as ROS. It also allows one to open the code base in popular editors such as CLion or Qtcreator. Lastly, it allows more people to jump on board for the code

**Comment by CLeechELEC** [comment]
Thanks, looks like it would be very useful. I'll look into it for the next update.
